@url_dev=http://localhost:3056/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json

{
  "shop_name": "Shop dev",
  "email": "duys2nqtnhmt@gmail.com",
  "password": "abcd1234"
}